[workspace]
resolver = "2"
members  = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

# [package]
# name = "api-key-finder"
# version = "0.1.0"
# edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
key_finder = { path = "crates/key_finder" }

anyhow              = { version = "1.0.82", features = ["backtrace"] }
clap                = { version = "4.5.4", features = ["derive", "color"] }
clap-verbosity-flag = { version = "2.2.0" }
csv                 = { version = "1.3.0" }
dashmap             = { version = "5.5.3", features = ["rayon"] }
ego-tree            = { version = "0.6.2" }
log                 = { version = "0.4.21", features = ["kv"] }
miette              = { version = "7.2.0", features = ["fancy", "syntect-highlighter"] }
oxc                 = { version = "0.11.1", features = ["semantic"] }
pretty_env_logger   = { version = "0.5.0" }
rand                = { version = "0.8.5" }
rayon               = { version = "1.10.0" }
regex               = { version = "1.10.4", features = ["perf-dfa-full"] }
scraper             = { version = "0.19.0" }
serde               = { version = "1.0.197", features = ["derive"] }
thiserror           = { version = "1.0.58" }
tinyvec             = { version = "1.6.0", features = ["alloc", "serde", "rustc_1_40"] }
toml                = { version = "0.8.12" }
ureq                = { version = "2.9.6", features = ["cookies"], default-features = true }
url                 = { version = "2.5.0" }

[profile.release]
lto = "fat"
