[workspace]
resolver = "2"
members  = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

# [package]
# name = "api-key-finder"
# version = "0.1.0"
# edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow            = { version = "1.0.82", features = ["backtrace"] }
csv               = "1.3.0"
dashmap           = { version = "5.5.3", features = ["rayon"] }
log               = { version = "0.4.21", features = ["kv"] }
miette            = { version = "7.2.0", features = ["fancy"] }
oxc               = { version = "0.11.1", features = ["semantic"] }
pretty_env_logger = { version = "0.5.0" }
rand              = "0.8.5"
rayon             = "1.10.0"
regex             = { version = "1.10.4", features = ["perf-dfa-full"] }
serde             = { version = "1.0.197", features = ["derive"] }
thiserror         = { version = "1.0.58" }
tinyvec           = { version = "1.6.0", features = ["alloc", "serde", "rustc_1_40"] }
toml              = { version = "0.8.12" }
ureq              = { version = "2.9.6", features = ["cookies"], default-features = true }
url               = { version = "2.5.0" }
scraper           = { version = "0.19.0" }
ego-tree          = { version = "0.6.2" }

[profile.release]
lto = "fat"
