[workspace]
resolver = "2"
members  = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

# [package]
# name = "api-key-finder"
# version = "0.1.0"
# edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow      = { version = "1.0.82", features = ["backtrace"] }
csv         = "1.3.0"
html_parser = "0.7.0"
oxc         = { version = "0.11.1", features = ["semantic"] }
rand        = "0.8.5"
rayon       = "1.10.0"
regex       = { version = "1.10.4" }
reqwest     = "0.12.3"
serde       = { version = "1.0.197", features = ["derive"] }
thiserror   = { version = "1.0.58" }
tinyvec     = { version = "1.6.0", features = ["alloc", "serde", "rustc_1_40"] }
tokio       = { version = "1.37.0", features = ["full"] }
toml        = { version = "0.8.12" }
ureq        = { version = "2.9.6", features = ["cookies"], default-features = true }
url         = { version = "2.5.0" }

[profile.release]
lto = "fat"
