name: CI Check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - run: cargo fmt --check
            - run: cargo test --all-features
